name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2 # Use the Terraform version you're working with

      # Step 3: Run terraform fmt to ensure proper formatting
      - name: Terraform FMT
        run: terraform fmt -check -recursive

      # Step 4: Run terraform validate to validate the configuration
      - name: Terraform Validate
        run: terraform validate

